[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting = "DHt4nNcMmkc1BGtkxPyPJm656ScJdrcQJzPhsLURTEY3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"